# 基本設定
baseURL = "https://pullmay.github.io/blog"
title = "みるログ"
theme = "hermit"
publishDir = "docs"
defaultContentLanguage = "ja"
hasCJKLanguage = true # ワードカウント
enableEmoji = true
paginate = 20

# 外部リンクを新規タブで開く
[blackfriday]
hrefTargetBlank = true

# シンタックスハイライト有効化とスタイル
# pygmentsCodefences = true
# pygmentsStyle = "manni"

[taxonomies]
tag = "tags"

[author]
	name = "pullmay"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    homeSubtitle = "stay gold"
    wordCount = true
    justifyContent = false

[Permalinks]
    post = "/:filename/"

[menu]
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 1
        pre = "<i class='fa fa-archive'></i>"

    [[menu.main]]
        name = "About"
        url = "/about/about/"
        weight = 2
        pre = "<i class='fa fa-info-circle'></i>"

    [[menu.main]]
        name = "みるログ"
        url = "/millog/"
        weight = 3
        pre = "<i class='fa fa-archive'></i>"
    
    [[menu.main]]
        name = "Note"
        url = "/notes/"
        weight = 4