# 基本設定
baseURL = "https://pullmay.github.io/blog"
title = "みるかのブログ"
theme = "hermit"
publishDir = "docs"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
hasCJKLanguage = true
enableEmoji = true

# 外部リンクを新規タブで開く
[blackfriday]
hrefTargetBlank = true

# シンタックスハイライト有効化とスタイル
pygmentsCodefences = true
pygmentsStyle = "manni"

[author]
	name = "pullmay"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    homeSubtitle = "stay gold"

    justifyContent = false

    Twitter  = "mirucaaura"
    footline = "Copyright&copy; <a href='/about/about/'>pullmay</a>"

[menu]
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 10
        pre = "<i class='fa fa-archive'></i>"

    [[menu.main]]
        name = "About"
        url = "/about/about/"
        weight = 10
        pre = "<i class='fa fa-info-circle'></i>"

    [[menu.main]]
        name = "みるログ"
        url = "/MiLLog/"
        weight = 10
        pre = "<i class='fa fa-archive'></i>"