# 基本設定
baseURL = "https://pullmay.github.io/blog"
langageCode = "ja-jP"
defaultContentLanguage = "ja"
title = "Flavor of Life"
theme = "hermit"
publishDir = "docs"

hasCJKLanguage = true # ワードカウント
enableEmoji = true
paginate = 20

# 外部リンクを新規タブで開く
[blackfriday]
hrefTargetBlank = true

# シンタックスハイライト有効化とスタイル
# pygmentsStyle = "default"
pygmentsUseClasses = true
pygmentsCodefences = true 

[taxonomies]
tag = "tags"

[author]
	name = "pullmay"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    homeSubtitle = "May the Utada be with you"
    wordCount = true
    justifyContent = false

[Permalinks]
    post = "/:filename/"

[menu]
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 1
        pre = "<i class='fa fa-archive'></i>"

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2
        pre = "<i class='fa fa-info-circle'></i>"

    [[menu.main]]
        name = "Log"
        url = "/millog/"
        weight = 3
        pre = "<i class='fa fa-archive'></i>"
    
    [[menu.main]]
        name = "tweets"
        url = "/tweets/"
        weight = 4
        pre = "<i class='fa fa-archive'></i>"